INSERT INTO  publishers (publisherName, publisherAddress, publisherPhone, publisherEmail) values ('Penguin Random House','1160 Trademark Dr # 111, Reno, NV 89521','909-123-1234','PRH@gmail.com'),
INSERT INTO  publishers (publisherName, publisherAddress, publisherPhone, publisherEmail) values ('Hachette Livre','100 Eden Pkwy EC4Y 0DZ Seattle USA','425-123-5555','HL@gmail.com'),
INSERT INTO  publishers (publisherName, publisherAddress, publisherPhone, publisherEmail) values ('HarperCollins', '1234 Moran Street, AL 36117','555-545-4525','email@harpercollins.com'),
INSERT INTO  publishers (publisherName, publisherAddress, publisherPhone, publisherEmail) values ('Macmillan Publishers', '120 Broadway, New York, NY','888-330-8477','MP@gmail.com'),
INSERT INTO  publishers (publisherName, publisherAddress, publisherPhone, publisherEmail) values ('Simon & Schuster','1230 6th Ave, New York, NY 10020','800-223-2336','SS@gmail.com');




INSERT INTO  books (groupName, bookTitle, publisherName, yearPublished,numberPages) VALUES  ('The Scribble Society','In Search of Lost Time','Penguin Random House', 1913 , 345),
INSERT INTO  books (groupName, bookTitle, publisherName, yearPublished,numberPages) VALUES  ('The Scribble Society','Ulysses','Penguin Random House', 1900 , 205),
INSERT INTO  books (groupName, bookTitle, publisherName, yearPublished,numberPages) VALUES  ('Masters of Text','Don Quixote','Hachette Livre', 2003 , 803),
INSERT INTO  books (groupName, bookTitle, publisherName, yearPublished,numberPages) VALUES  ('From Left to Write','The Great Gatsby','HarperCollins', 2005 , 736),
INSERT INTO  books (groupName, bookTitle, publisherName, yearPublished,numberPages) VALUES  ('Always Write','One Hundred Years of Solitude','HarperCollins', 1990 , 404),
INSERT INTO  books (groupName, bookTitle, publisherName, yearPublished,numberPages) VALUES  ('Plot Twists','Moby Dick','Macmillan Publishers', 2005 , 777),
INSERT INTO  books (groupName, bookTitle, publisherName, yearPublished,numberPages) VALUES  ('Novice Narrators','One Hundred Years of Solitude','Macmillan Publishers', 1994 , 673),
INSERT INTO  books (groupName, bookTitle, publisherName, yearPublished,numberPages) VALUES  ('Masters of Text','Hamlet','Simon & Schuster', 2003 , 1111),
INSERT INTO  books (groupName, bookTitle, publisherName, yearPublished,numberPages) VALUES  ('The Pencil Pack','The Catcher in the Rye','Simon & Schuster', 2008 , 568);